// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWWuY6QpckHCQRtliuXKg8WBY4f3iP8_o',
    appId: '1:180002560540:web:bd8ea9936afcfa8bed5dd9',
    messagingSenderId: '180002560540',
    projectId: 'flutter-mart-fa313',
    authDomain: 'flutter-mart-fa313.firebaseapp.com',
    storageBucket: 'flutter-mart-fa313.appspot.com',
    measurementId: 'G-RLQJ0L3G2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBIP2hS2c5g4kzFEVf7Gl8-uq9oIgKWxQ',
    appId: '1:180002560540:android:5475dc3feb3c8f3ced5dd9',
    messagingSenderId: '180002560540',
    projectId: 'flutter-mart-fa313',
    storageBucket: 'flutter-mart-fa313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbT36tE26TUeod18Zr6MG0M7VCIYOC77I',
    appId: '1:180002560540:ios:fc822b5d0ddc00f2ed5dd9',
    messagingSenderId: '180002560540',
    projectId: 'flutter-mart-fa313',
    storageBucket: 'flutter-mart-fa313.appspot.com',
    iosBundleId: 'com.vaibhav.fluttermart.flutterMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbT36tE26TUeod18Zr6MG0M7VCIYOC77I',
    appId: '1:180002560540:ios:fc822b5d0ddc00f2ed5dd9',
    messagingSenderId: '180002560540',
    projectId: 'flutter-mart-fa313',
    storageBucket: 'flutter-mart-fa313.appspot.com',
    iosBundleId: 'com.vaibhav.fluttermart.flutterMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWWuY6QpckHCQRtliuXKg8WBY4f3iP8_o',
    appId: '1:180002560540:web:cb4534553abafc48ed5dd9',
    messagingSenderId: '180002560540',
    projectId: 'flutter-mart-fa313',
    authDomain: 'flutter-mart-fa313.firebaseapp.com',
    storageBucket: 'flutter-mart-fa313.appspot.com',
    measurementId: 'G-DCFX58Z9TS',
  );
}
